services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lol-api
    restart: on-failure
    depends_on:
      - db
    environment:
      CHAT_SERVICE_URL: ${CHAT_SERVICE_URL:-https://example.com}
      CHAT_SERVICE_KEY: ${CHAT_SERVICE_KEY:-key}
    ports:
      - 8080:8080
  db:
    image: postgres:17-alpine
    restart: on-failure
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-lol}
    ports:
      - ${DB_PORT:-3003}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3