server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:3003/lol
    username: postgres
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

logging:
    level:
      sql: debug